USE [master]
GO

/****** Object:  Database [TALIS_FAST_FOOD]    Script Date: 25/9/2023 15:49:09 ******/
CREATE DATABASE [TALIS_FAST_FOOD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TALIS_FAST_FOOD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER2019\MSSQL\DATA\TALIS_FAST_FOOD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TALIS_FAST_FOOD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER2019\MSSQL\DATA\TALIS_FAST_FOOD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TALIS_FAST_FOOD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET ARITHABORT OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET RECOVERY FULL 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET  MULTI_USER 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TALIS_FAST_FOOD] SET  READ_WRITE 
GO


