//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_TIPO_PAGO
    {
        public int ID_FACTURA { get; set; }
        public int ID_TIPO_PAGO { get; set; }
        public double MONTO { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual TIPO_PAGO TIPO_PAGO { get; set; }
    }
}
