//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.FACTURA_TIPO_PAGO = new HashSet<FACTURA_TIPO_PAGO>();
        }
    
        public int ID_FACTURA { get; set; }
        public double SUBTOTAL { get; set; }
        public double IMPUESTO { get; set; }
        public double TOTAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_ORDEN { get; set; }
        public int ID_MESA { get; set; }
        public string ID_USUARIO { get; set; }
    
        public virtual MESA MESA { get; set; }
        public virtual ORDEN ORDEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_TIPO_PAGO> FACTURA_TIPO_PAGO { get; set; }
    }
}
